# action.yml
name: 'Run In Cypress'
description: 'Run your UI Tests in cypress with included chrome browser'
inputs:
  port-to-run-on:
    description: 'The Port where the internal server runs on.'
    required: true
    default: '3000'
  source-directory:
    description: 'The Directory where the source files are kept.'
    required: true
    default: 'src'
  browser-to-use:
    description: 'The Browser to use, currently only electron and chrome are available.'
    required: true
    default: 'chrome'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.port-to-run-on }}
    - ${{ inputs.source-directory }}
    - ${{ inputs.browser-to-use }}
